"""add card_types table

Revision ID: 2dca638dae28
Revises: 
Create Date: 2026-07-23 12:13:49.900567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dca638dae28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_types',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('sell_value', sa.Integer(), nullable=False),
    sa.Column('nutrition_turns', sa.Integer(), nullable=True),
    sa.Column('base_output_points', sa.Integer(), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=False),
    sa.Column('accent_color', sa.String(length=64), nullable=False),
    sa.Column('background_color', sa.String(length=64), nullable=False),
    sa.Column('is_tradeable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_types')
    # ### end Alembic commands ###
