"""add card pools, hands, player economy

Revision ID: 94295213d683
Revises: 0239c6d1d8a8
Create Date: 2026-07-24 01:09:23.033846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94295213d683'
down_revision: Union[str, Sequence[str], None] = '0239c6d1d8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_card_pools',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('card_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_pool_non_negative'),
    sa.ForeignKeyConstraint(['card_type'], ['card_types.code'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'card_type')
    )
    op.create_table('player_hands',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('card_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_hand_non_negative'),
    sa.CheckConstraint('reserved_quantity <= quantity', name='ck_hand_reserved_le_qty'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_hand_reserved_non_negative'),
    sa.ForeignKeyConstraint(['card_type'], ['card_types.code'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['game_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', 'card_type')
    )
    op.add_column('game_players', sa.Column('points', sa.Integer(), nullable=False))
    op.add_column('game_players', sa.Column('reserved_points', sa.Integer(), nullable=False))
    op.add_column('game_players', sa.Column('food_due', sa.Integer(), nullable=False))
    op.add_column('game_players', sa.Column('rent_due', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_players', 'rent_due')
    op.drop_column('game_players', 'food_due')
    op.drop_column('game_players', 'reserved_points')
    op.drop_column('game_players', 'points')
    op.drop_table('player_hands')
    op.drop_table('game_card_pools')
    # ### end Alembic commands ###
