"""add trade offers

Revision ID: b2158ed730e0
Revises: dc78c6f0b9b1
Create Date: 2026-07-24 20:07:57.715137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2158ed730e0'
down_revision: Union[str, Sequence[str], None] = 'dc78c6f0b9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('poster_player_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('offer_card_type', sa.String(length=32), nullable=False),
    sa.Column('offer_quantity', sa.Integer(), nullable=False),
    sa.Column('price_points', sa.Integer(), nullable=True),
    sa.Column('want_card_type', sa.String(length=32), nullable=True),
    sa.Column('want_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claimed_by_player_id', sa.UUID(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_with_player_id', sa.UUID(), nullable=True),
    sa.Column('created_turn', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(kind = 'sell' AND price_points IS NOT NULL AND want_card_type IS NULL) OR (kind = 'trade' AND want_card_type IS NOT NULL AND price_points IS NULL)", name='ck_offer_shape'),
    sa.CheckConstraint("(status = 'claimed') = (claimed_by_player_id IS NOT NULL)", name='ck_offer_claim_consistent'),
    sa.CheckConstraint('offer_quantity > 0', name='ck_offer_qty_positive'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_card_type'], ['card_types.code'], ),
    sa.ForeignKeyConstraint(['poster_player_id'], ['game_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['want_card_type'], ['card_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_offers_game_id'), 'trade_offers', ['game_id'], unique=False)
    op.create_index(op.f('ix_trade_offers_poster_player_id'), 'trade_offers', ['poster_player_id'], unique=False)
    op.create_index(op.f('ix_trade_offers_status'), 'trade_offers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_offers_status'), table_name='trade_offers')
    op.drop_index(op.f('ix_trade_offers_poster_player_id'), table_name='trade_offers')
    op.drop_index(op.f('ix_trade_offers_game_id'), table_name='trade_offers')
    op.drop_table('trade_offers')
    # ### end Alembic commands ###
