"""add card pools, hands, player economy

Revision ID: e9a9cb5ebeec
Revises: 94295213d683
Create Date: 2026-07-24 01:16:47.952403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a9cb5ebeec'
down_revision: Union[str, Sequence[str], None] = '94295213d683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('turn_number', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('phase', sa.String(length=16), nullable=False))
    op.add_column('games', sa.Column('current_player_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_games_current_player', 'games', 'game_players', ['current_player_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_games_current_player', 'games', type_='foreignkey')
    op.drop_column('games', 'current_player_id')
    op.drop_column('games', 'phase')
    op.drop_column('games', 'turn_number')
    # ### end Alembic commands ###
